# Simple Production Docker Compose - SIP Proxy Only
# Deploy this first, add Kamailio later

services:
  # SIP Proxy Web Service - Main application
  sip-proxy-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: sip-proxy-app-production
    restart: unless-stopped
    ports:
      - "3001:3000" # HTTP API
      - "5061:5060" # SIP Signaling
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      - TARGET_SIP_SERVER=asterisk-service.ada-asia.my:5060
      - CORS_ORIGIN=https://yourdomain.com
    networks:
      - sip-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # WebRTC Bridge - WebSocket server for browsers
  webrtc-bridge:
    build:
      context: ./app
      dockerfile: Dockerfile.webrtc
    container_name: webrtc-bridge-production
    restart: unless-stopped
    ports:
      - "8081:8080" # WebSocket port
    environment:
      - NODE_ENV=production
      - PORT=8080
      - SIP_PROXY_URL=http://sip-proxy-app:3000
      - CORS_ORIGIN=https://yourdomain.com
    depends_on:
      - sip-proxy-app
    networks:
      - sip-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  sip-network:
    driver: bridge
