version: '3.8'

services:
  rtpengine:
    image: sippy/rtpengine:latest
    container_name: rtpengine
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    volumes:
      - ./rtpengine/rtpengine.conf:/etc/rtpengine/rtpengine.conf:ro
      - ./rtpengine/rtpengine.pid:/var/run/rtpengine.pid
      - rtpengine-data:/var/spool/rtpengine
    command: >
      --config-file=/etc/rtpengine/rtpengine.conf
      --pid-file=/var/run/rtpengine.pid
      --interface=0.0.0.0
      --listen-ng=127.0.0.1:22222
      --listen-udp=0.0.0.0:12222
      --listen-tcp=0.0.0.0:12222
      --listen-cli=127.0.0.1:22223
      --foreground
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

  rtpengine-worker-1:
    image: sippy/rtpengine:latest
    container_name: rtpengine-worker-1
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    volumes:
      - ./rtpengine/rtpengine.conf:/etc/rtpengine/rtpengine.conf:ro
      - ./rtpengine/rtpengine-worker-1.pid:/var/run/rtpengine.pid
      - rtpengine-data:/var/spool/rtpengine
    command: >
      --config-file=/etc/rtpengine/rtpengine.conf
      --pid-file=/var/run/rtpengine.pid
      --interface=0.0.0.0
      --listen-ng=127.0.0.1:22225
      --listen-udp=0.0.0.0:12223
      --listen-tcp=0.0.0.0:12223
      --listen-cli=127.0.0.1:22226
      --foreground
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

  rtpengine-worker-2:
    image: sippy/rtpengine:latest
    container_name: rtpengine-worker-2
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    volumes:
      - ./rtpengine/rtpengine.conf:/etc/rtpengine/rtpengine.conf:ro
      - ./rtpengine/rtpengine-worker-2.pid:/var/run/rtpengine.pid
      - rtpengine-data:/var/spool/rtpengine
    command: >
      --config-file=/etc/rtpengine/rtpengine.conf
      --pid-file=/var/run/rtpengine.pid
      --interface=0.0.0.0
      --listen-ng=127.0.0.1:22227
      --listen-udp=0.0.0.0:12224
      --listen-tcp=0.0.0.0:12224
      --listen-cli=127.0.0.1:22228
      --foreground
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

  drachtio-server:
    image: drachtio/drachtio-server:latest
    container_name: drachtio-server
    network_mode: host
    volumes:
      - ./drachtio/drachtio.conf.xml:/etc/drachtio/drachtio.conf.xml:ro
    command: drachtio --config /etc/drachtio/drachtio.conf.xml
    restart: unless-stopped
    depends_on:
      - rtpengine
      - rtpengine-worker-1
      - rtpengine-worker-2
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  sip-proxy-app:
    build: .
    container_name: sip-proxy-app
    network_mode: host
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - RTPENGINE_HOST=127.0.0.1
      - RTPENGINE_PORT=22222
      - RTPENGINE_WORKER_1_HOST=127.0.0.1
      - RTPENGINE_WORKER_1_PORT=22225
      - RTPENGINE_WORKER_2_HOST=127.0.0.1
      - RTPENGINE_WORKER_2_PORT=22227
      - DRACHTIO_HOST=127.0.0.1
      - DRACHTIO_PORT=9022
      - TARGET_SIP_SERVER=asterisk-service.ada-asia.my:5060
    restart: unless-stopped
    depends_on:
      - drachtio-server
      - rtpengine
      - rtpengine-worker-1
      - rtpengine-worker-2
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Load balancer for RTPEngine workers
  rtpengine-lb:
    image: nginx:alpine
    container_name: rtpengine-lb
    network_mode: host
    volumes:
      - ./rtpengine/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - rtpengine
      - rtpengine-worker-1
      - rtpengine-worker-2

volumes:
  rtpengine-data:

networks:
  default:
    driver: bridge
